version: "3.7"

services:
    bulphp:
        image: "bulphp:1.0"
        ports:
            - 80:80
        volumes:
            - "/project/web:/var/www/html:ro"
        networks:
            - bul-network
        depends_on:
            - bulmysql
        environment:
            MYSQL_DATABASE: bulgaria
            MYSQL_USER: web_user
            MYSQL_PASSWORD: Password1

    bulmysql:
        image: "bulsql:1.0"
        environment:
            MYSQL_ROOT_PASSWORD: nE5kMc7JCGNqwDQN
        networks:
            - bul-network

networks:
    bul-network:
