apiVersion: apps/v1
kind: Deployment
metadata:
  name: dob-mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dob-mysql
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: dob-mysql
    spec:
      containers:
        - env:
          - name: MYSQL_ROOT_PASSWORD
            value: "nE5kMc7JCGNqwDQN"
          name: dob-mysql
          image: chonochonov/dob-mysql:%IMAGE-PLACEHOLDER%
          ports:
          - containerPort: 3306
---
apiVersion: v1
kind: Service
metadata:
  name: dob-mysql
  labels:
    app: dob-mysql
spec:
  ports:
    - port: 3306
      targetPort: 3306
      name: tcp-3306
  selector:
      app: dob-mysql