apiVersion: apps/v1
kind: Deployment
metadata:
  name: dob-php
spec:
  replicas: 3
  selector:
    matchLabels:
      app: dob-php
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: dob-php
    spec:
      containers:
        - env:
          - name: MYSQL_PASSWORD
            value: Password1
            name: MYSQL_USER
            value: web_user
            name: MYSQL_DATABASE
            value: bulgaria
        - name: dob-php
          image: chonochonov/dob-php:%IMAGE-PLACEHOLDER%
          volumeMounts:
          - mountPath: /var/www/html/
            name: git-volume
            subPath: "DevOpsDocker/web/"
          ports:
          - containerPort: 80
      volumes:
      - name: git-volume
        gitRepo:
          repository: "https://github.com/chonochonovuk/DevOpsDocker"
          revision: main
---
apiVersion: v1
kind: Service
metadata:
  name: dob-php
  labels:
    app: dob-php
spec:
  type: NodePort
  ports:
    - port: 80
      nodePort: 30007
      name: http-80
  selector:
    app: dob-php
